{% set name = "ml-insights" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ml_insights-{{ version }}.tar.gz
  sha256: 5e903a35ea121e2f1b1460b19ca93ef093508df97ceea96a5a00e624784acaad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
    - numpy
  run:
    - matplotlib-base >=2.0.0
    - scikit-learn >=0.24.2
    - {{ pin_compatible('numpy') }}
    - pandas >=0.23
    - python >=3.4
    - scipy >=1.6.0
    - splinecalib >=0.0.6

test:
  imports:
    - ml_insights
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://ml-insights.readthedocs.io/en/latest/
  summary: Package to calibrate and understand ML Models
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/numeristical/introspective

extra:
  recipe-maintainers:
    - philip-khor
