{% set name = "ml-insights" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ml_insights-{{ version }}.tar.gz
  sha256: cac33eefa32fb30909280b58ed2e73a6dd8def863a2f4c392b876c50b5972ef1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - matplotlib-base >=2.0.0
    - scikit-learn >=0.24.2
    - numpy >=1.16.0
    - pandas >=0.23
    - python >=3.4
    - scipy >=1.6.0
    - splinecalib >=0.0.2

test:
  imports:
    - ml_insights
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://ml-insights.readthedocs.io/en/latest/
  summary: Package to calibrate and understand ML Models
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/numeristical/introspective

extra:
  recipe-maintainers:
    - philip-khor
